name: "DICL: MPI Sintel"
id: dicl/sintel-0

data:
  source: ../../data/train-sintel.yaml
  epochs: 100
  batch-size: 1

optimizer:
  type: adam-w

  parameters:
    lr: 0.001
    weight_decay: 0.0001
    eps: 1.0e-9

model:
  arguments:
    raw: false

loss:
  arguments:
    weights: [1.0, 0.75, 0.5, 0.5, 0.5]
    valid_range: [[372, 372], [360, 360], [336, 336], [288, 288], [192, 192]]

gradient:
  clip:
    type: norm
    value: 1.0

  accumulate: 2

lr-scheduler:
  instance:
    - type: one-cycle
      parameters:
        max_lr: 0.001
        total_steps: '{n_samples} + 100'
        pct_start: 0.05
        cycle_momentum: false
        anneal_strategy: linear
