mode: continuous

stages:
  - name: "MPI Sintel (clean, full augmentations)"
    id: train/sintel-0

    data:
      source: ../../data/mpi-sintel-clean.train.aug-full.yaml
      epochs: 100
      batch-size: 1

    validation:
      source: ../../data/mpi-sintel-clean.val.yaml
      batch-size: 1
      images: [0, 24, 49, 74, 99]

    optimizer:
      type: adam-w

      parameters:
        lr: &learning_rate 1.25e-4
        weight_decay: 1.0e-5
        eps: 1.0e-8

    lr-scheduler:
      instance:
        - type: one-cycle
          parameters:
            max_lr: *learning_rate
            total_steps: '({n_epochs} * {n_batches}) // {n_accum} + 100'
            pct_start: 0.05
            cycle_momentum: false
            anneal_strategy: linear

    gradient:
      clip:
        type: norm
        value: 1.0
