mode: continuous

stages:
  - name: "FlyingChairs2 (full augmentations)"
    id: train/chairs2-0

    data:
      source: ../../data/ufreiburg-flyingchairs2.train.aug-full.yaml
      epochs: 25
      batch-size: 2

    validation:
      source: ../../data/ufreiburg-flyingchairs2.test.yaml
      batch-size: 1
      images: [0, 24, 49, 74, 99]

    optimizer:
      type: adam-w

      parameters:
        lr: 1.0e-4
        weight_decay: 0.0
        betas: [0.9, 0.999]
        eps: 1.0e-8

    gradient:
      clip:
        type: norm
        value: 1.0
