mode: continuous

stages:
  - name: "FlyingChairs2 (basic augmentations only with forwards-backwards batching, 1 layer)"
    id: train/chairs2-0.0

    data:
      source:
        type: subset
        size: 9000
        source: ../../data/ufreiburg-flyingchairs2.train.aug-basic.fwbw.yaml
      epochs: 1
      batch-size: 3   # Note: this will create a batch size of 6 due to forward-backward matching

    validation:
      source: ../../data/ufreiburg-flyingchairs2.test.yaml
      batch-size: 4
      images: [0, 24, 49, 74, 99]

    optimizer:
      type: adam-w

      parameters:
        lr: 4.0e-4
        weight_decay: 0.0
        eps: 1.0e-8

    gradient:
      clip:
        type: norm
        value: 1.0

    model:
      arguments:
        iterations: [0, 0, 0, 3]
        upnet: false

    loss:
      arguments:
        alpha: [0.0, 0.0, 0.0, 1.0]

  - name: "FlyingChairs2 (basic augmentations only with forwards-backwards batching, 2 layer)"
    id: train/chairs2-0.1

    data:
      source:
        type: subset
        size: 9000
        source: ../../data/ufreiburg-flyingchairs2.train.aug-basic.fwbw.yaml
      epochs: 1
      batch-size: 3   # Note: this will create a batch size of 6 due to forward-backward matching

    validation:
      source: ../../data/ufreiburg-flyingchairs2.test.yaml
      batch-size: 4
      images: [0, 24, 49, 74, 99]

    optimizer:
      type: adam-w

      parameters:
        lr: 4.0e-4
        weight_decay: 0.0
        eps: 1.0e-8

    gradient:
      clip:
        type: norm
        value: 1.0

    model:
      arguments:
        iterations: [0, 0, 4, 3]
        upnet: false

    loss:
      arguments:
        alpha: [0.0, 0.0, 1.0, 0.1]

  - name: "FlyingChairs2 (basic augmentations only with forwards-backwards batching, 3 layer)"
    id: train/chairs2-0.2

    data:
      source:
        type: subset
        size: 9000
        source: ../../data/ufreiburg-flyingchairs2.train.aug-basic.fwbw.yaml
      epochs: 1
      batch-size: 3   # Note: this will create a batch size of 6 due to forward-backward matching

    validation:
      source: ../../data/ufreiburg-flyingchairs2.test.yaml
      batch-size: 4
      images: [0, 24, 49, 74, 99]

    optimizer:
      type: adam-w

      parameters:
        lr: 4.0e-4
        weight_decay: 0.0
        eps: 1.0e-8

    gradient:
      clip:
        type: norm
        value: 1.0

    model:
      arguments:
        iterations: [0, 4, 4, 3]
        upnet: false

    loss:
      arguments:
        alpha: [0.0, 1.0, 0.01, 0.01]

  - name: "FlyingChairs2 (basic augmentations only with forwards-backwards batching, 4 layer)"
    id: train/chairs2-0.3

    data:
      source:
        type: subset
        size: 9000
        source: ../../data/ufreiburg-flyingchairs2.train.aug-basic.fwbw.yaml
      epochs: 1
      batch-size: 3   # Note: this will create a batch size of 6 due to forward-backward matching

    validation:
      source: ../../data/ufreiburg-flyingchairs2.test.yaml
      batch-size: 4
      images: [0, 24, 49, 74, 99]

    optimizer:
      type: adam-w

      parameters:
        lr: 4.0e-4
        weight_decay: 0.0
        eps: 1.0e-8

    gradient:
      clip:
        type: norm
        value: 1.0

    model:
      arguments:
        iterations: [3, 4, 4, 3]
        upnet: false

    loss:
      arguments:
        alpha: [1.0, 0.01, 0.01, 0.01]

  - name: "FlyingChairs2 (basic augmentations only with forwards-backwards batching)"
    id: train/chairs2-0.4

    data:
      source: ../../data/ufreiburg-flyingchairs2.train.aug-basic.fwbw.yaml
      epochs: 1
      batch-size: 3   # Note: this will create a batch size of 6 due to forward-backward matching

    validation:
      source: ../../data/ufreiburg-flyingchairs2.test.yaml
      batch-size: 4
      images: [0, 24, 49, 74, 99]

    optimizer:
      type: adam-w

      parameters:
        lr: &learning_rate1 4.0e-4
        weight_decay: 1.0e-4
        eps: 1.0e-8

    lr-scheduler:
      instance:
        - type: one-cycle
          parameters:
            max_lr: *learning_rate1
            total_steps: '({n_epochs} * {n_batches}) // {n_accum} + 100'
            pct_start: 0.05
            cycle_momentum: false
            anneal_strategy: linear

    gradient:
      clip:
        type: norm
        value: 1.0

  - name: "FlyingChairs2 (fully augmented)"
    id: train/chairs2-1

    data:
      source: ../../data/ufreiburg-flyingchairs2.train.aug-full.yaml
      epochs: 14      # ~100k steps
      batch-size: 6

    validation:
      source: ../../data/ufreiburg-flyingchairs2.test.yaml
      batch-size: 4
      images: [0, 24, 49, 74, 99]

    optimizer:
      type: adam-w

      parameters:
        lr: &learning_rate2 4.0e-4
        weight_decay: 1.0e-4
        eps: 1.0e-8

    lr-scheduler:
      instance:
        - type: one-cycle
          parameters:
            max_lr: *learning_rate2
            total_steps: '({n_epochs} * {n_batches}) // {n_accum} + 100'
            pct_start: 0.05
            cycle_momentum: false
            anneal_strategy: linear

    gradient:
      clip:
        type: norm
        value: 1.0
