mode: continuous
stages:
  - name: "RAFT: Stage 1: Uni Freiburg FlyingThings"
    id: raft/s1-things

    data:
      epochs: 15        # ~ 600k samples or 100k steps
      batch-size: 6

      source:
        type: augment

        source:
          type: concat
          sources:
            - ../../../data/ufreiburg-flyingthings3d-clean.train.yaml
            - ../../../data/ufreiburg-flyingthings3d-final.train.yaml

        augmentations:
          - type: color-jitter-8bit
            prob-asymmetric: 0.2
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1592   # 0.5 / pi

          - type: occlusion-forward
            probability: 0.5
            num: [1, 3]
            min-size: [50, 50]
            max-size: [100, 100]
            skew-correction: false

          - type: scale-exp
            min-size: [728, 408]    # size + 8
            min-scale: -0.4
            max-scale: 0.8
            max-stretch: 0.2
            prob-stretch: 0.8

          - type: flip
            probability: [0.5, 0.1]

          - type: crop
            size: [720, 400]

          - type: restrict-flow-magnitude
            maximum: 400

    validation:
      - name: sintel-clean
        source: ../../../data/mpi-sintel-clean.train-full.yaml
        batch-size: 2
        images: [0, 512, 1024]

      - name: sintel-final
        source: ../../../data/mpi-sintel-final.train-full.yaml
        batch-size: 2
        images: [0, 512, 1024]


    model:
      on-stage:
        freeze_batchnorm: true

    loss:
      arguments:
        gamma: 0.8

    optimizer:
      type: adam-w

      parameters:
        lr: &learning_rate 0.000125
        weight_decay: 0.0001
        eps: 1.0e-8

    lr-scheduler:
      instance:
        - type: one-cycle
          parameters:
            max_lr: *learning_rate
            total_steps: '100000 + 100'
            pct_start: 0.05
            cycle_momentum: false
            anneal_strategy: linear

    gradient:
      clip:
        type: norm
        value: 1.0
