name: "RAFT: Stage 2: MPI Sintel"
id: raft/s2-sintel

data:
  epochs: 3           # ~ 600k samples or 100k steps
  batch-size: 6

  source:
    type: augment

    source:
      type: concat

      sources:
        - type: augment         # full flow datasets

          augmentations:
            - type: scale
              min-size: &img_size [768, 368]
              min-scale: 0.87
              max-scale: 1.52
              max-stretch: 0.2
              prob-stretch: 0.8

          source:               # 100 * sintel_clean + 100 * sintel_final + things
            type: concat
            sources:
              - type: repeat
                times: 100
                source: ../../../data/mpi-sintel-clean.train-full.yaml

              - type: repeat
                times: 100
                source: ../../../data/mpi-sintel-final.train-full.yaml

              - ../../../data/ufreiburg-flyingthings3d-clean.train.yaml

        - type: concat          # sparse flow datasets: 200 * kitti + 5 * hd1k
          sources:
            - type: augment

              augmentations:
                - type: scale-sparse
                  min-size: *img_size
                  min-scale: 0.81
                  max-scale: 1.41
                  max-stretch: 0.2
                  prob-stretch: 0.8

              source:
                type: repeat
                times: 200
                source: ../../../data/kitti-2012.train.yaml

            - type: augment

              augmentations:
                - type: scale-sparse
                  min-size: *img_size
                  min-scale: 0.71
                  max-scale: 1.15
                  max-stretch: 0.2
                  prob-stretch: 0.8

              source:
                type: repeat
                times: 5
                source: ../../../data/hci-hd1k.yaml

    augmentations:              # general augmentations
      - type: crop
        size: *img_size

      - type: flip
        probability: [0.5, 0.1]

      - type: color-jitter
        prob-asymmetric: 0.2
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1592   # 0.5 / pi

      - type: occlusion-forward
        probability: 0.5
        num: [1, 3]
        min-size: [1, 1]
        max-size: [100, 50]

validation:
  - name: sintel-clean
    source: ../../data/mpi-sintel-clean.train-full.yaml
    batch-size: 2
    images: [0, 512, 1024]

  - name: sintel-final
    source: ../../data/mpi-sintel-final.train-full.yaml
    batch-size: 2
    images: [0, 512, 1024]

loss:
  arguments:
    gamma: 0.85

optimizer:
  type: adam-w

  parameters:
    lr: &learning_rate 0.000125
    weight_decay: 0.00001
    eps: 1.0e-8

lr-scheduler:
  instance:
    - type: one-cycle
      parameters:
        max_lr: *learning_rate
        total_steps: '({n_epochs} * {n_batches}) // {n_accum} + 100'
        pct_start: 0.05
        cycle_momentum: false
        anneal_strategy: linear

gradient:
  clip:
    type: norm
    value: 1.0
