mode: continuous
stages:
  - name: "RAFT: Stage 2: MPI Sintel"
    id: raft/s2-sintel

    data:
      epochs: 3           # ~ 600k samples or 100k steps
      batch-size: 6

      source:
        type: augment

        source:
          type: concat

          sources:
            - type: augment         # full flow datasets

              augmentations:
                - type: color-jitter
                  prob-asymmetric: 0.2
                  brightness: 0.4
                  contrast: 0.4
                  saturation: 0.4
                  hue: 0.1592   # 0.5 / pi

                - type: occlusion-forward
                  probability: 0.5
                  num: [1, 3]
                  min-size: [50, 50]
                  max-size: [100, 100]
                  skew-correction: false

                - type: scale-exp
                  min-size: [776, 376]      # size + 8
                  min-scale: -0.2
                  max-scale: 0.6
                  max-stretch: 0.2
                  prob-stretch: 0.8

              source:               # 100 * sintel_clean + 100 * sintel_final + things
                type: concat
                sources:
                  - type: repeat
                    times: 100
                    source: ../../../data/mpi-sintel-clean.train-full.yaml

                  - type: repeat
                    times: 100
                    source: ../../../data/mpi-sintel-final.train-full.yaml

                  - ../../../data/ufreiburg-flyingthings3d-clean.train.yaml

            - type: concat          # sparse flow datasets: 200 * kitti + 5 * hd1k
              sources:
                - type: augment

                  augmentations:
                    - type: color-jitter
                      prob-asymmetric: 0.2
                      brightness: 0.4
                      contrast: 0.4
                      saturation: 0.4
                      hue: 0.1592   # 0.5 / pi

                    - type: occlusion-forward
                      probability: 0.5
                      num: [1, 3]
                      min-size: [50, 50]
                      max-size: [100, 100]
                      skew-correction: false

                    - type: scale-sparse-exp
                      min-size: [776, 376]      # size + 8
                      min-scale: -0.3
                      max-scale: 0.5
                      max-stretch: 0.0
                      prob-stretch: 0.0

                  source:
                    type: repeat
                    times: 200
                    source: ../../../data/kitti-2015.train.yaml

                - type: augment

                  augmentations:
                    - type: color-jitter
                      prob-asymmetric: 0.2
                      brightness: 0.4
                      contrast: 0.4
                      saturation: 0.4
                      hue: 0.1592   # 0.5 / pi

                    - type: occlusion-forward
                      probability: 0.5
                      num: [1, 3]
                      min-size: [50, 50]
                      max-size: [100, 100]
                      skew-correction: false

                    - type: scale-sparse-exp
                      min-size: [776, 376]      # size + 8
                      min-scale: -0.5
                      max-scale: 0.2
                      max-stretch: 0.0
                      prob-stretch: 0.0

                  source:
                    type: repeat
                    times: 5
                    source: ../../../data/hci-hd1k.yaml

        augmentations:              # general augmentations
          - type: flip
            probability: [0.5, 0.1]

          - type: crop
            size: [768, 368]

    validation:
      - name: sintel-clean
        source: ../../../data/mpi-sintel-clean.train-full.yaml
        batch-size: 2
        images: [0, 512, 1024]

      - name: sintel-final
        source: ../../../data/mpi-sintel-final.train-full.yaml
        batch-size: 2
        images: [0, 512, 1024]

    model:
      on-stage:
        freeze_batchnorm: true

    loss:
      arguments:
        gamma: 0.85

    optimizer:
      type: adam-w

      parameters:
        lr: &learning_rate 0.000125
        weight_decay: 0.00001
        eps: 1.0e-8

    lr-scheduler:
      instance:
        - type: one-cycle
          parameters:
            max_lr: *learning_rate
            total_steps: '100000 + 100'
            pct_start: 0.05
            cycle_momentum: false
            anneal_strategy: linear

    gradient:
      clip:
        type: norm
        value: 1.0
